on:
    push:
        branches:
            - main

# Environment variables available to all jobs and steps in this workflow
env:
  GCLOUD_PROJECT: ${{ secrets.GKE_PROJECT }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  GITHUB_SHA: ${{ github.sha }}
  IMAGE: gkeapp
  SERVICE: gke-service
  DIRECTORY: run
   
name: Demos 1 - Build and Deploy

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
          
        - name: Setup Cloud SDK
          uses: google-github-actions/setup-gcloud@v0.2.0
          with:
            project_id: ${{ secrets.GKE_PROJECT }}
            service_account_key: ${{ env.GCP_SA_KEY }}
            export_default_credentials: true
            
        - name: Set project
          run: |- 
            gcloud config set project ${{ secrets.GKE_PROJECT }}
           
        - name: Authorize Docker push
          run: gcloud auth configure-docker

        - name: Build and Push Container
          run: |-
            #docker build -t --tag=gcr.io/${{ secrets.GKE_PROJECT }}/${{ env.IMAGE }}:${{ env.GITHUB_SHA }} .
            #docker push gcr.io/${{ secrets.GKE_PROJECT }}/${{ env.IMAGE }}:${{ env.GITHUB_SHA }}
            gcloud builds submit ${{ env.DIRECTORY }} --tag=gcr.io/${{ secrets.GKE_PROJECT }}/${{ env.IMAGE }}:${{ env.GITHUB_SHA }}
            
        - name: Deploy to Cloud Run
          id: deploy
          uses: google-github-actions/deploy-cloudrun@v0.2.0
          with:
                service: ${{ env.SERVICE }}
                image: gcr.io/${{ secrets.GKE_PROJECT }}/${{ env.IMAGE }}:${{ env.GITHUB_SHA }}
                #env_vars: TITLE=Demo 1, SECRET=${{ secrets.SECRET_NAME }}
                
        - name: Show Output
          run: 'curl "${{ steps.deploy.outputs.url }}"'
          
        #- name: Allow unauthenticated
          #run: |-
            #gcloud run deploy ${{ env.SERVICE }} --allow-unauthenticated
                
  
                          
